apiVersion: apps/v1
kind: Deployment
metadata:
  name: mido-docker-app
  labels:
    app: mido-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mido-docker-app
  template:
    metadata:
      labels:
        app: mido-docker-app
    spec:
      containers:
      - name: mido-docker-app
        image: ghcr.io/adineba90/mido-docker-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mido-docker-app-service
spec:
  selector:
    app: mido-docker-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer